[package]
name = "little_exif"

version = "0.6.0-beta.4"
edition = "2021"

description = """
Basic reading and writing of EXIF metadata for PNG, JP(E)G, JXL and WebP images
(other file types - e.g. TIFF or HEIC - are planned) written in pure Rust.
"""

authors = ["Tobias Prisching"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/TechnikTobi/little_exif"
readme = "README.md"
keywords = ["metadata", "exif", "photo", "image"]
categories = ["multimedia::images"]

exclude = [
    ".DS_Store",
    "**/.DS_Store",
    ".gitignore",
    "additional-documentation/*",
    "tests/*",
    "debug/*",
    ".cargo_vcs_info.json",
]

[dependencies]
crc = "3.0.0"
paste = "1.0.9"
miniz_oxide = "0.8.0"

[[test]]
name = "tests"
path = "tests/main.rs"