[package]
name = "little_exif"

version = "0.6.0"
edition = "2021"
rust-version = "1.65"

description = """
Basic reading and writing of EXIF metadata for PNG, JP(E)G, JXL, TIFF and WebP 
images (other file types like HEIC are in development) written in pure Rust.
"""

authors = ["Tobias Prisching"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/TechnikTobi/little_exif"
readme = "README.md"
keywords = ["metadata", "exif", "photo", "image"]
categories = ["multimedia::images"]

exclude = [
    ".DS_Store",
    "**/.DS_Store",
    ".gitignore",
    "additional-documentation/*",
    "tests/*",
    "debug/*",
    ".cargo_vcs_info.json",
]

[dependencies]
crc = "3.2.1"
paste = "1.0.15"
miniz_oxide = "0.8.0"

[[test]]
name = "tests"
path = "tests/main.rs"