[package]
name = "little-exif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0.0"
paste = "1.0.9"
miniz_oxide = "0.6.2"

# Disable testing of the examples mentioned in the documentation
[lib]
doctest = false

[[test]]
name = "tests"
path = "tests/main.rs"